--tabla: jugador

CREATE TABLE JUGADOR(
  ID_JUGADOR NUMBER(4) CONSTRAINT JUGADOR_PK PRIMARY KEY,
  NOMBRE VARCHAR2(70) CONSTRAINT JUGADOR_NOMBRE_NN NOT NULL,
  EDAD NUMBER(3) CONSTRAINT JUGADOR_EDAD_NN NOT NULL,
  PARTIDOS_JUGADOS NUMBER(2) DEFAULT 0 CONSTRAINT JUGADOR_PARTIDOSJ_NN NOT NULL,
  GOLES NUMBER(3) DEFAULT 0 CONSTRAINT JUGADOR_GOLES_NN NOT NULL,
  ASISTENCIAS NUMBER(3) DEFAULT 0 CONSTRAINT JUGADOR_ASIST_NN NOT NULL,
  TARJETAS_ROJAS NUMBER(3) DEFAULT 0 CONSTRAINT JUGADOR_TARROJA_NN NOT NULL,
  TARJETAS_AMARILLAS NUMBER(3) DEFAULT 0 CONSTRAINT JUGADOR_TARAM_NN NOT NULL,
  ID_EQUIPO NUMBER(4),
  CONSTRAINT EQUIPO_JUGADOR_FK FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);
DESC JUGADOR;



--tabla: equipo

CREATE TABLE EQUIPO(
  ID_EQUIPO NUMBER(4) CONSTRAINT EQUIPO_PK PRIMARY KEY,
  NOMBRE VARCHAR2(70) CONSTRAINT EQUIPO_NOMBRE_NN NOT NULL,
  VICTORIAS NUMBER(2) DEFAULT 0 CONSTRAINT EQUIPO_VICTORIAS_NN NOT NULL,
  DERROTAS NUMBER(2)DEFAULT 0 CONSTRAINT EQUIPO_DERROTAS_NN NOT NULL,
  EMPATES NUMBER(2)DEFAULT 0 CONSTRAINT EQUIPO_EMPATES_NN NOT NULL,
  GOLES_FAVOR NUMBER(3) DEFAULT 0 CONSTRAINT EQUIPO_GOLESF_NN NOT NULL,
  GOLES_CONTRA NUMBER(3) DEFAULT 0 CONSTRAINT EQUIPO_GOLESC_NN NOT NULL
);

DESC EQUIPO;

CREATE TABLE TIPO_EVENTO(
  ID_TIPOEVENTO NUMBER(1) CONSTRAINT TIPO_EVENTO PRIMARY KEY,
  DESCRIPCION VARCHAR2(70) CONSTRAINT TIPOE_DESC_NN NOT NULL
);
DESC TIPO_EVENTO;

CREATE TABLE PARTIDO(
  ID_PARTIDO NUMBER(4) CONSTRAINT PARTIDO_PK PRIMARY KEY,
  FECHA DATE,
  EQUIPO_LOCAL NUMBER(4) CONSTRAINT PARTIDO_EQLOCAL_NN NOT NULL,
  EQUIPO_VISITANTE NUMBER(4)CONSTRAINT PARTIDO_EQVISITANTE_NN NOT NULL,
  JORNADA NUMBER(2),
  COMPLETADO NUMBER(1) DEFAULT 0 CONSTRAINT PARTIDO_COMPLETADO_NN NOT NULL,
  GOLES_LOCAL NUMBER(2) CONSTRAINT PARTIDO_GOLLOC_NN NOT NULL,
  GOLES_VISITANTE NUMBER(2) CONSTRAINT PARTIDO_GOLVIS_NN NOT NULL,
  CONSTRAINT EQUIPO_PARTIDO_EL_FK FOREIGN KEY (EQUIPO_LOCAL) REFERENCES EQUIPO(ID_EQUIPO),
  CONSTRAINT EQUIPO_PARTIDO_EV_FK FOREIGN KEY (EQUIPO_VISITANTE) REFERENCES EQUIPO(ID_EQUIPO)
);

DESC PARTIDO;

CREATE TABLE EVENTO(
  ID_EVENTO NUMBER(5) CONSTRAINT EVENTO_PK PRIMARY KEY,
  ID_TIPOEVENTO NUMBER(1)CONSTRAINT EVENTO_TE_NN NOT NULL,
  JUGADOR_PRINCIPAL NUMBER(4) CONSTRAINT EVENTO_JUGP_NN NOT NULL,
  JUGADOR_SECUNDARIO NUMBER(4) CONSTRAINT EVENTO_JUGS_NN NOT NULL,
  MINUTO NUMBER(3) CONSTRAINT EVENTO_MINUTO_NN NOT NULL,
  ID_PARTIDO NUMBER(4) CONSTRAINT EVENTO_IDPARTIDO_NN NOT NULL,
  CONSTRAINT TE_EVENTO_FK FOREIGN KEY (ID_TIPOEVENTO) REFERENCES TIPO_EVENTO(ID_TIPOEVENTO),
  CONSTRAINT JUGADOR_EVENTO_JP_FK FOREIGN KEY (JUGADOR_PRINCIPAL) REFERENCES JUGADOR(ID_JUGADOR),
  CONSTRAINT JUGADOR_EVENTO_JS_FK FOREIGN KEY (JUGADOR_SECUNDARIO) REFERENCES JUGADOR(ID_JUGADOR),
  CONSTRAINT PARTIDO_EVENTO_FK FOREIGN KEY (ID_PARTIDO) REFERENCES PARTIDO(ID_PARTIDO)
);
DESC EVENTO;

CREATE TABLE CUENTAS_ADMIN(
  ID_CUENTA NUMBER(5) CONSTRAINT CUENTAS_ADMIN_PK PRIMARY KEY,
  NOMBRE VARCHAR(50) CONSTRAINT CUENTAS_ADMIN_NOM_NN NOT NULL,
  CONTRASENA VARCHAR(40) CONSTRAINT CUENTAS_ADMIN_CONTRA_NN NOT NULL
);

DESC CUENTAS_ADMIN;


